<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Locker admin</h1>

      <form action="/admin/files" method="post" enctype="multipart/form-data">
        <div class="form-group">
          <label for="title">タイトル</label>
          <input type="text" name="title" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="description">説明 (optional)</label>
          <textarea name="description" class="form-control"></textarea>
        </div>
        <div class="form-group">
          <label for="file">ファイル</label>
          <input type="file" name="file" class="form-control-file" required>
        </div>
        <div class="form-group">
          <label for="passphrase">パスフレーズ (optional)</label>
          <input type="password" name="passphrase" class="form-control">
        </div>
        <div class="form-group">
          <label for="expires_at">有効期限</label>
          <input type="datetime-local" name="expires_at" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">保存</button>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>


