<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= $title ?></title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
  </head>
  <body>
    <h1><?= $title ?></h1>

    <footer>
      <p><a href="https://github.com/riaf/locker">Powered by Locker.</a></p>
    </footer>
  </body>
</html>
